Give each redshift client their own boto session
fishtown-analytics/dbt pull request #2766
Opened 2020-09-17 09:00 UTC by jweibel22

since the boto session is not thread-safe, using the default session in a multi-threaded scenario will result in concurrency errors

resolves #2756

### Description
Instantiates a fresh session before creating the client. This is similar to what is happening in the else branch. Thus, this change should not cause any unexpected issues (e.g. exceeding service quotas)

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

2020-09-17 17:05 UTC, jtcohen6 commented
@jweibel22 Nice! I'd love to get this in for v0.18.1. Does this change work for you locally when you run with multiple threads?

Also, could you:
- pull changes from `dev/0.18.1` (which should include fixes to the failing Redshift integration tests)
- add a changelog entry under v0.18.1

2020-09-18 12:43 UTC, jweibel22 commented
> @jweibel22 Nice! I'd love to get this in for v0.18.1. Does this change work for you locally when you run with multiple threads?

Yes, I have verified that is does resolve the issue when I run `dbt compile` locally.

2020-09-18 13:44 UTC, beckjake requested changes
This looks very nice!

Could you add a test to the redshift unit tests in `tests/unit/test_redshift_adapter.py` that makes sure we call `boto3.Session().client()`  instead of `boto3.client()` directly in both the iam_profile  cases (none and not none)? I would hate to regress on this.

2020-09-18 13:44 UTC, beckjake commented on CHANGELOG.md
> +- `dbt compile` and `dbt run` failed with `KeyError: 'endpoint_resolver'` when threads > 1 and `method: iam` had been specified in the profiles.yaml ([#2766](https://github.com/fishtown-analytics/dbt
```suggestion
- `dbt compile` and `dbt run` failed with `KeyError: 'endpoint_resolver'` when threads > 1 and `method: iam` had been specified in the profiles.yaml ([#2756](https://github.com/fishtown-analytics/dbt/issues/2756), [#2766](https://github.com/fishtown-analytics/dbt/pull/2766))
```

We usually also include a link to the issue in the changelog

2020-09-21 13:32 UTC, beckjake approved these changes
Thanks! This looks great to me

2020-09-25 16:10 UTC, jtcohen6 approved these changes
Thanks for this @jweibel22! I'll try to resolve the changelog conflict and get this in.

2020-09-25 16:50 UTC, merged