Fix incorrect error message (trivial)
fishtown-analytics/dbt pull request #3036
Opened 2021-01-27 21:11 UTC by ran-eh

resolves #

### Description

### Checklist
 - [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

2021-01-28 13:26 UTC, jtcohen6 reviewed
Thanks for the PR @ran-eh! I'm not opposed to changing this error message in the spirit of making it clearer. I am curious to hear, in what way do you feel that the current language is incorrect?

Because `alert_non_existence` adjudicates each of (potentially many) selection criteria, it's possible that one criterion does not match any nodes while another does. To my mind, the phrase `nothing to do` is a bit confusing in such a case:
```bash
$ dbt run -m fct_sprints asdfgh
...
The selector 'asdfgh' does not match any nodes - nothing to do

14:21:31 | Concurrency: 8 threads (target='dev')
14:21:31 |
14:21:31 | 1 of 1 START table model dbt_jcohen.fct_sprints...................... [RUN]
```

Perhaps we could simplify this message to just: `The selection criterion 'asdfgh' does not match any nodes`. (While we're here, we may as well disambiguate from YAML `selectors` / `--selector`, too.)

2021-01-28 19:23 UTC, ran-eh commented
> Thanks for the PR @ran-eh! I'm not opposed to changing this error message in the spirit of making it clearer. I am curious to hear, in what way do you feel that the current language is incorrect?
> 
> Because `alert_non_existence` adjudicates each of (potentially many) selection criteria, it's possible that one criterion does not match any nodes while another does. To my mind, the phrase `nothing to do` is a bit confusing in such a case:
> 
> ```shell
> $ dbt run -m fct_sprints asdfgh
> ...
> The selector 'asdfgh' does not match any nodes - nothing to do
> 
> 14:21:31 | Concurrency: 8 threads (target='dev')
> 14:21:31 |
> 14:21:31 | 1 of 1 START table model dbt_jcohen.fct_sprints...................... [RUN]
> ```
> 
> Perhaps we could simplify this message to just: `The selection criterion 'asdfgh' does not match any nodes`. (While we're here, we may as well disambiguate from YAML `selectors` / `--selector`, too.)

Agreed and changed.

2021-02-08 11:27 UTC, jtcohen6 approved these changes
Thanks for this @ran-eh!

2021-02-09 16:02 UTC, jtcohen6 requested changes
Whoops, sorry for the over-eager approval. One tiny change and then this should be fit to ship.

2021-02-09 16:02 UTC, jtcohen6 commented on core/dbt/graph/selector.py
> +            f"The selection criterion '{str(raw_spec)}' does not match any nodes"
`flake8` just takes issue with this line being two characters too long:
```
core/dbt/graph/selector.py:28:80: E501 line too long (81 > 79 characters)
```
So perhaps:
```suggestion
            f"The selection criterion '{str(raw_spec)}' does not match"
            f" any nodes"
```

2021-02-10 11:00 UTC, jtcohen6 approved these changes

2021-02-10 11:00 UTC, merged